apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-ui=acrdevfronttodoapp01.azurecr.io/todo-ui
    argocd-image-updater.argoproj.io/todo-ui.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: acrdevfronttodoapp01.azurecr.io/todo-ui: v4
        ports:
        - containerPort: 80

